import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const b612Mono = localFont({
//     src: [
//         {
//             path: "/fonts/b612-mono/b612-mono-400-normal.ttf",
//             weight: "400",
//             style: "normal",
//         },
//         {
//             path: "/fonts/b612-mono/b612-mono-700-normal.ttf",
//             weight: "700",
//             style: "normal",
//         },
//     ],
// });
//
// const glassTTY = localFont({
//     src: [
//         {
//             path: "/fonts/glass-tty-vt220/glass-tty-vt220-500-normal.woff",
//             weight: "500",
//             style: "normal",
//         },
//     ],
// });
//
// const RobotoMono = localFont({
//     src: [
//         {
//             path: "/fonts/roboto-mono/roboto-mono-300-normal.ttf",
//             weight: "300",
//             style: "normal",
//         },
//         {
//             path: "/fonts/roboto-mono/roboto-mono-400-normal.ttf",
//             weight: "400",
//             style: "normal",
//         },
//         {
//             path: "/fonts/roboto-mono/roboto-mono-700-normal.ttf",
//             weight: "700",
//             style: "normal",
//         },
//     ],
// });

// console.log(RobotoMono);

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`font-b612mono antialiased`}>
                <p>here is some writing</p>
                {children}
            </body>
        </html>
    );
}
