import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-robotomono antialiased">
                <header className="w-full border py-16 px-6">
                    <div className="mx-auto max-w-4xl">
                        <h1>Brian Siklinski</h1>
                        <h2>web developer</h2>
                    </div>
                </header>
                {children}
                <footer className="border py-16 px-6">
                    <p className="font-glasstty mx-auto max-w-4xl text-center">
                        © 2025 bsik.net | All Rights Reserved | Designed by
                        Lubna Sarigat
                    </p>
                </footer>
            </body>
        </html>
    );
}
