import type { Metadata } from "next";
import Header from "./parts/header";
import Footer from "./parts/footer";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-robotomono antialiased">
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
